### ISSUE TITLE
optuna_constraint.pyの実行時のエラーについて

### ISSUE THREAD

**Issue by NMDsato** [HideakiImamura/bo-book#1]
お世話になります。

section4/optuna_constraint.pyをダウンロードして実行してみましたが、エラーとなりました。
エラー文は以下のとおりです。

ImportError: logei_candidates_func requires botorch >=0.8.1. Please upgrade botorch or use qei_candidates_func as candidates_func instead.

ということで、requirements.txtにはbotorch>=0.4.0,<0.8.0とありましたが、 botorchの0.8.1をインストールして再度optuna_constraint.pyを実行したところエラーはでなくなりました。
しかし、今度はsection4/botorch_simple.pyが実行できなくなりました。botorchのバージョンを0.7.3に戻すとbotorch_simple.pyはエラーなく実行できました。

結局のところbotorchのバージョンはいくつにしておくべきでしょうか？
また、botorchのバージョンが決まったとして、上述のようにoptuna_constraint.pyとbotorch_simple.pyのいずれかは実行できなくなると思うのですが、コード自体をどのように修正すればよいでしょうか？

**Comment by HideakiImamura** [comment]
こちら確認遅れまして申し訳ございません。

optunaのBoTorchSamplerはまだ実験的な機能なためアップデートが頻繁に入っており、そのためoptunaの2024/03/11時点の最新バージョン3.5.0ではコードが壊れていました。先ほどアップデートしたので、これで動くかと思います。

**Comment by NMDsato** [comment]
ご回答頂きまして、ありがとうございます。こちらのコードを参考にいたします。
